import { MORPHQL_LANGUAGE } from "./src/index";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const distDir = path.resolve(__dirname, "dist");
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

// 1. Export JSON
const jsonPath = path.resolve(distDir, "morphql-lang.json");
fs.writeFileSync(jsonPath, JSON.stringify(MORPHQL_LANGUAGE, null, 2));
console.log(`Language definitions exported to ${jsonPath}`);

// 2. Export Kotlin Constants
const constantsPath = path.resolve(
  __dirname,
  "../jetbrains-extension/src/main/kotlin/org/morphql/jetbrains/MorphQLConstants.kt",
);

const keywords = MORPHQL_LANGUAGE.keywords.map((k) => k.name);
const functions = MORPHQL_LANGUAGE.functions.map((f) => f.name);
const operators = MORPHQL_LANGUAGE.operators.map((o) => o.symbol);

const constantsContent = `package org.morphql.jetbrains

/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by packages/language-definitions/export-json.ts
 */
object MorphQLConstants {
    val KEYWORDS = setOf(
${keywords.map((k) => `        "${k}"`).join(",\n")}
    )

    val FUNCTIONS = setOf(
${functions.map((f) => `        "${f}"`).join(",\n")}
    )

    val OPERATORS = setOf(
${operators.map((o) => `        "${o}"`).join(",\n")}
    )
}
`;

if (fs.existsSync(path.dirname(constantsPath))) {
  fs.writeFileSync(constantsPath, constantsContent);
  console.log(`Kotlin constants exported to ${constantsPath}`);
}

// 3. Export Kotlin Documentation
const docsPath = path.resolve(
  __dirname,
  "../jetbrains-extension/src/main/kotlin/org/morphql/jetbrains/MorphQLDocumentation.kt",
);

const allDocs: Record<string, any> = {};
MORPHQL_LANGUAGE.keywords.forEach((k) => {
  allDocs[k.name] = k.doc;
});
MORPHQL_LANGUAGE.functions.forEach((f) => {
  allDocs[f.name] = f.doc;
});

const escapeQuotes = (str: string) =>
  str.replace(/"/g, '\\"').replace(/\n/g, "\\n");

const docsEntries = Object.entries(allDocs)
  .map(([name, doc]) => {
    return `        "${name}" to """
            <b>${doc.signature}</b><br/>
            ${doc.description}<br/><br/>
            ${
              doc.parameters && doc.parameters.length > 0
                ? `<b>Parameters:</b><ul>${doc.parameters
                    .map(
                      (p: any) => `<li><b>${p.name}:</b> ${p.description}</li>`,
                    )
                    .join("")}</ul>`
                : ""
            }
            ${doc.example ? `<b>Example:</b><pre>${doc.example}</pre>` : ""}
        """.trimIndent()`;
  })
  .join(",\n");

const docsContent = `package org.morphql.jetbrains

/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by packages/language-definitions/export-json.ts
 */
object MorphQLDocumentation {
    val DOCS = mapOf(
${docsEntries}
    )
}
`;

if (fs.existsSync(path.dirname(docsPath))) {
  fs.writeFileSync(docsPath, docsContent);
  console.log(`Kotlin documentation exported to ${docsPath}`);
}
