package org.morphql.jetbrains

/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by packages/language-definitions/export-json.ts
 */
object MorphQLDocumentation {
    val DOCS = mapOf(
        "from" to """
            <b>from <format></b><br/>
            Specifies the input data format.<br/><br/>
            <b>Parameters:</b><ul><li><b>format:</b> If used as first keyword: The starting format name (e.g., `json`, `xml`, `csv`, `object`). When used after a section, defines its source.</li></ul>
            <b>Example:</b><pre>from json to csv</pre>
        """.trimIndent(),
        "to" to """
            <b>to <format></b><br/>
            Specifies the output data format.<br/><br/>
            <b>Parameters:</b><ul><li><b>format:</b> The name of one of the available adapters.</li></ul>
            <b>Example:</b><pre>from csv to json</pre>
        """.trimIndent(),
        "transform" to """
            <b>transform [unsafe]</b><br/>
            Begins the transformation block containing actions. Optional 'unsafe' keyword disables safety features (optional chaining) for maximum performance.<br/><br/>
            
            <b>Example:</b><pre>transform
  set name = firstName

transform unsafe
  set result = price / quantity</pre>
        """.trimIndent(),
        "unsafe" to """
            <b>transform unsafe</b><br/>
            Disables safety features (optional chaining) in generated code for maximum performance. Use only with validated/trusted input data.<br/><br/>
            
            <b>Example:</b><pre>transform unsafe
  set result = price / quantity</pre>
        """.trimIndent(),
        "set" to """
            <b>set <target> = <expression></b><br/>
            Assigns a value to a field in the output.<br/><br/>
            <b>Parameters:</b><ul><li><b>target:</b> The field name to set</li><li><b>expression:</b> The value or expression to assign</li></ul>
            <b>Example:</b><pre>set fullName = firstName + " " + lastName</pre>
        """.trimIndent(),
        "section" to """
            <b>section [multiple] <name>( [subquery] <actions> ) [from <path>]</b><br/>
            Creates a nested object or array in the output. Can optionally include a subquery for format conversion.<br/><br/>
            <b>Parameters:</b><ul><li><b>multiple:</b> (Optional) Treat as array mapping</li><li><b>name:</b> The section/field name</li><li><b>subquery:</b> (Optional) Nested query: from <format> to <format> [transform]</li><li><b>actions:</b> Actions to perform within the section</li><li><b>from:</b> (Optional) Source path for the section data</li></ul>
            <b>Example:</b><pre>section items(
  from csv to object
  transform
    set name = A
) from csvString</pre>
        """.trimIndent(),
        "multiple" to """
            <b>section multiple <name>(...)</b><br/>
            Modifier for `section` to map over an array.<br/><br/>
            
            <b>Example:</b><pre>section multiple items(
  set id = itemId
) from products</pre>
        """.trimIndent(),
        "clone" to """
            <b>clone([field1, field2, ...])</b><br/>
            Copies fields from the source to the output.<br/><br/>
            <b>Parameters:</b><ul><li><b>fields:</b> (Optional) Specific fields to clone. If omitted, clones all fields.</li></ul>
            <b>Example:</b><pre>clone(id, name, email)</pre>
        """.trimIndent(),
        "delete" to """
            <b>delete <field></b><br/>
            Removes a field from the output (useful after `clone`).<br/><br/>
            <b>Parameters:</b><ul><li><b>field:</b> The field name to delete</li></ul>
            <b>Example:</b><pre>clone()
delete password</pre>
        """.trimIndent(),
        "define" to """
            <b>define <alias> = <expression></b><br/>
            Creates a local variable/alias for use in subsequent expressions.<br/><br/>
            <b>Parameters:</b><ul><li><b>alias:</b> The variable name</li><li><b>expression:</b> The value to assign</li></ul>
            <b>Example:</b><pre>define taxRate = 0.22
set totalWithTax = total * (1 + taxRate)</pre>
        """.trimIndent(),
        "if" to """
            <b>if (condition) ( actions ) [else ( actions )]</b><br/>
            Conditional execution of action blocks.<br/><br/>
            <b>Parameters:</b><ul><li><b>condition:</b> Boolean expression</li><li><b>actions:</b> Actions to execute if true/false</li></ul>
            <b>Example:</b><pre>if (age >= 18) (
  set status = "adult"
) else (
  set status = "minor"
)</pre>
        """.trimIndent(),
        "else" to """
            <b>else ( actions )</b><br/>
            Defines the else branch of an `if` statement.<br/><br/>
            
            <b>Example:</b><pre>if (condition) (
  ...
) else (
  ...
)</pre>
        """.trimIndent(),
        "modify" to """
            <b>modify <target> = <expression></b><br/>
            Modifies a field in the output by reading from the target (not source). Useful for post-processing already-mapped values.<br/><br/>
            <b>Parameters:</b><ul><li><b>target:</b> The field name to modify</li><li><b>expression:</b> The expression to assign (reads from target, not source)</li></ul>
            <b>Example:</b><pre>set total = price * quantity
modify total = total * 1.10</pre>
        """.trimIndent(),
        "substring" to """
            <b>substring(str, start, [length])</b><br/>
            Extracts a portion of a string. Supports negative indices.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The source string</li><li><b>start:</b> Starting index (0-based, negative counts from end)</li><li><b>length:</b> (Optional) Number of characters to extract</li></ul>
            <b>Example:</b><pre>substring("Hello World", 0, 5)  // "Hello"
substring("Hello World", -5)     // "World"</pre>
        """.trimIndent(),
        "split" to """
            <b>split(str, [separator], [limit])</b><br/>
            Splits a string into an array.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to split</li><li><b>separator:</b> (Optional) Delimiter string. Default: ""</li><li><b>limit:</b> (Optional) Maximum number of splits</li></ul>
            <b>Example:</b><pre>split("a,b,c", ",")  // ["a", "b", "c"]</pre>
        """.trimIndent(),
        "replace" to """
            <b>replace(str, search, replacement)</b><br/>
            Replaces occurrences in a string.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The source string</li><li><b>search:</b> The substring to find</li><li><b>replacement:</b> The replacement string</li></ul>
            <b>Example:</b><pre>replace("Hello World", "World", "MorphQL")  // "Hello MorphQL"</pre>
        """.trimIndent(),
        "text" to """
            <b>text(value)</b><br/>
            Converts a value to a string.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The value to convert</li></ul>
            <b>Example:</b><pre>text(123)  // "123"</pre>
        """.trimIndent(),
        "number" to """
            <b>number(value)</b><br/>
            Converts a value to a number.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The value to convert</li></ul>
            <b>Example:</b><pre>number("42")  // 42</pre>
        """.trimIndent(),
        "uppercase" to """
            <b>uppercase(str)</b><br/>
            Converts a string to uppercase.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to convert</li></ul>
            <b>Example:</b><pre>uppercase("hello")  // "HELLO"</pre>
        """.trimIndent(),
        "lowercase" to """
            <b>lowercase(str)</b><br/>
            Converts a string to lowercase.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to convert</li></ul>
            <b>Example:</b><pre>lowercase("HELLO")  // "hello"</pre>
        """.trimIndent(),
        "extractnumber" to """
            <b>extractnumber(str)</b><br/>
            Extracts the first numeric sequence from a string.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to extract from</li></ul>
            <b>Example:</b><pre>extractnumber("Price: 100USD")  // 100</pre>
        """.trimIndent(),
        "xmlnode" to """
            <b>xmlnode(value, [attrKey, attrVal, ...])</b><br/>
            Wraps a value for XML output with optional attributes.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The node content</li><li><b>attrKey, attrVal:</b> (Optional) Pairs of attribute keys and values</li></ul>
            <b>Example:</b><pre>xmlnode(content, "id", 1, "type", "text")</pre>
        """.trimIndent(),
        "to_base64" to """
            <b>to_base64(value)</b><br/>
            Encodes a string value to Base64.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The string to encode</li></ul>
            <b>Example:</b><pre>to_base64("hello")  // "aGVsbG8="</pre>
        """.trimIndent(),
        "from_base64" to """
            <b>from_base64(value)</b><br/>
            Decodes a Base64 string value.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The Base64 string to decode</li></ul>
            <b>Example:</b><pre>from_base64("aGVsbG8=")  // "hello"</pre>
        """.trimIndent(),
        "aslist" to """
            <b>aslist(value)</b><br/>
            Ensures a value is an array. Useful for input formats like XML that might return a single object or an array for the same field.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The value to normalize</li></ul>
            <b>Example:</b><pre>aslist(items)  // Always returns an array</pre>
        """.trimIndent()
    )
}
