package org.morphql.jetbrains

/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by packages/language-definitions/export-json.ts
 */
object MorphQLConstants {
    val KEYWORDS = setOf(
        "from",
        "to",
        "transform",
        "unsafe",
        "set",
        "section",
        "multiple",
        "clone",
        "delete",
        "define",
        "if",
        "else",
        "modify"
    )

    val FUNCTIONS = setOf(
        "substring",
        "split",
        "replace",
        "text",
        "number",
        "uppercase",
        "lowercase",
        "extractnumber",
        "xmlnode",
        "to_base64",
        "from_base64",
        "aslist"
    )

    val OPERATORS = setOf(
        "===",
        "!==",
        "==",
        "!=",
        "<=",
        ">=",
        "<",
        ">",
        "&&",
        "||",
        "!",
        "+",
        "-",
        "*",
        "/",
        "="
    )
}
